apiVersion: v1 
kind: LimitRange
metadata: 
  name: limit
  namespace: black
spec: 
  limits: 
    - default: 
        cpu: 200m 
        memory: 500Mi
      defaultRequest: 
        cpu: 100m 
        memory: 250Mi 
#      min: 
#        cpu: 80m 
#        memory: 250Mi
      max: 
        cpu: 700m 
        memory: 700Mi
      type: Container
